### ISSUE TITLE
0.13 support

### ISSUE THREAD

**Issue by theoparis** [nitrogenez/nitrofetch#2]
Nice project! I found this when I was looking for a pure zig river WM configuration and I came across your repos.

Nitrofetch currently fails to build with zig >= 0.13 due to ComptimeStringMap being renamed. https://github.com/ziglang/zig/blob/0.13.0/lib/std/static_string_map.zig#L71

```diff
diff --git a/src/Logo.zig b/src/Logo.zig
index a4a343b..1aa280d 100644
--- a/src/Logo.zig
+++ b/src/Logo.zig
@@ -87,7 +87,7 @@ fn hckrPrint(comptime fmt: []const u8, args: anytype, w: anytype) !void {
     try w.writeAll("\x1B[0m");
 }
 
-pub const logos = std.ComptimeStringMap([]const u8, .{
+pub const logos = std.StaticStringMap([]const u8).initComptime(.{
     .{ "aix", @embedFile("logos/aix.ascii") },
     .{ "arch", @embedFile("logos/arch.ascii") },
     .{ "linux", @embedFile("logos/linux.ascii") },
```

**Comment by nitrogenez** [comment]
hi, thanks for coming by. i currently have no plans on supporting master version of zig at the moment, due to it being highly unstable. for the time being nitrofetch only compiles with zig 0.12.0 exactly.

the possible solution to your problem might be to make a ternary if statement checking the declaration existence. i will look into that.

**Comment by nitrogenez** [comment]
~Resolved in fb97f01.~ Thanks for participating.

**Comment by nitrogenez** [comment]
Just noticed that the initialization method had changed as well. This needs a little tweak.

**Comment by nitrogenez** [comment]
Finally resolved in 5008aff.

**Comment by theoparis** [comment]
Thanks! Just so you know 0.13 is actually a new release and is not from master.

**Comment by nitrogenez** [comment]
Has it released already? Oh, boy. Okay, then. I will migrate my projects to 0.13.0. I just thought that it was still on -dev branch. Thank you for noticing.
